In [21]:
import pandas as pd
from sklearn.model_selection import train_test_split

In [2]:
data=pd.read_table(r'C:\Users\SHASHWAT PANDEY\Desktop\car_eval.txt',sep=",",header=None)

In [3]:
data#6-Label 0-5 Features

          0      1      2     3      4     5      6
0     vhigh  vhigh      2     2  small   low  unacc
1     vhigh  vhigh      2     2  small   med  unacc
2     vhigh  vhigh      2     2  small  high  unacc
3     vhigh  vhigh      2     2    med   low  unacc
4     vhigh  vhigh      2     2    med   med  unacc
5     vhigh  vhigh      2     2    med  high  unacc
6     vhigh  vhigh      2     2    big   low  unacc
7     vhigh  vhigh      2     2    big   med  unacc
8     vhigh  vhigh      2     2    big  high  unacc
9     vhigh  vhigh      2     4  small   low  unacc
10    vhigh  vhigh      2     4  small   med  unacc
11    vhigh  vhigh      2     4  small  high  unacc
12    vhigh  vhigh      2     4    med   low  unacc
13    vhigh  vhigh      2     4    med   med  unacc
14    vhigh  vhigh      2     4    med  high  unacc
15    vhigh  vhigh      2     4    big   low  unacc
16    vhigh  vhigh      2     4    big   med  unacc
17    vhigh  vhigh      2     4    big  high  unacc
18    vhigh  vhigh      2  more  small   low  unacc
19    vhigh  vhigh      2  more  small   med  unacc
20    vhigh  vhigh      2  more  small  high  unacc
21    vhigh  vhigh      2  more    med   low  unacc
22    vhigh  vhigh      2  more    med   med  unacc
23    vhigh  vhigh      2  more    med  high  unacc
24    vhigh  vhigh      2  more    big   low  unacc
25    vhigh  vhigh      2  more    big   med  unacc
26    vhigh  vhigh      2  more    big  high  unacc
27    vhigh  vhigh      3     2  small   low  unacc
28    vhigh  vhigh      3     2  small   med  unacc
29    vhigh  vhigh      3     2  small  high  unacc
...     ...    ...    ...   ...    ...   ...    ...
1698    low    low      4  more    big   low  unacc
1699    low    low      4  more    big   med   good
1700    low    low      4  more    big  high  vgood
1701    low    low  5more     2  small   low  unacc
1702    low    low  5more     2  small   med  unacc
1703    low    low  5more     2  small  high  unacc
1704    low    low  5more     2    med   low  unacc
1705    low    low  5more     2    med   med  unacc
1706    low    low  5more     2    med  high  unacc
1707    low    low  5more     2    big   low  unacc
1708    low    low  5more     2    big   med  unacc
1709    low    low  5more     2    big  high  unacc
1710    low    low  5more     4  small   low  unacc
1711    low    low  5more     4  small   med    acc
1712    low    low  5more     4  small  high   good
1713    low    low  5more     4    med   low  unacc
1714    low    low  5more     4    med   med   good
1715    low    low  5more     4    med  high  vgood
1716    low    low  5more     4    big   low  unacc
1717    low    low  5more     4    big   med   good
1718    low    low  5more     4    big  high  vgood
1719    low    low  5more  more  small   low  unacc
1720    low    low  5more  more  small   med    acc
1721    low    low  5more  more  small  high   good
1722    low    low  5more  more    med   low  unacc
1723    low    low  5more  more    med   med   good
1724    low    low  5more  more    med  high  vgood
1725    low    low  5more  more    big   low  unacc
1726    low    low  5more  more    big   med   good
1727    low    low  5more  more    big  high  vgood

[1728 rows x 7 columns]

In [4]:
print(type(data)) #Pandas dataframe

<class 'pandas.core.frame.DataFrame'>

In [5]:
print(data.shape)

(1728, 7)

In [6]:
data.describe()

           0     1     2     3      4     5      6
count   1728  1728  1728  1728   1728  1728   1728
unique     4     4     4     3      3     3      4
top     high  high     2     2  small  high  unacc
freq     432   432   432   576    576   576   1210

In [7]:
data[6].unique()

array(['unacc', 'acc', 'vgood', 'good'], dtype=object)

In [8]:
data.isnull().sum()

0    0
1    0
2    0
3    0
4    0
5    0
6    0
dtype: int64

In [9]:
#less than 40-50% NANS ko eliminate karo
# More than 50% NANS ko Common occurring value se bharo

In [10]:
df=pd.DataFrame(data) ##pandas dataframe
print(df[6].unique())##labels
df[3]=df[3].replace('more',5)
df[2]=df[2].replace('5more',5)
y_label=df[6]
del df[6]

['unacc' 'acc' 'vgood' 'good']

In [16]:
#df=pd.get_dummies(df,columns=[4_med],drop_first=True) ##one hot encoding the ordinal catagorical var
from sklearn import preprocessing
le = preprocessing.LabelEncoder() ##simple encoding of catagorical vars 
df[0]=le.fit_transform(df[0])
df[1]=le.fit_transform(df[1])
df[5]=le.fit_transform(df[5])
print(df.shape)

(1728, 7)

In [17]:
df

      0  1  2  3  5  4_med  4_small
0     3  3  2  2  1      0        1
1     3  3  2  2  2      0        1
2     3  3  2  2  0      0        1
3     3  3  2  2  1      1        0
4     3  3  2  2  2      1        0
5     3  3  2  2  0      1        0
6     3  3  2  2  1      0        0
7     3  3  2  2  2      0        0
8     3  3  2  2  0      0        0
9     3  3  2  4  1      0        1
10    3  3  2  4  2      0        1
11    3  3  2  4  0      0        1
12    3  3  2  4  1      1        0
13    3  3  2  4  2      1        0
14    3  3  2  4  0      1        0
15    3  3  2  4  1      0        0
16    3  3  2  4  2      0        0
17    3  3  2  4  0      0        0
18    3  3  2  5  1      0        1
19    3  3  2  5  2      0        1
20    3  3  2  5  0      0        1
21    3  3  2  5  1      1        0
22    3  3  2  5  2      1        0
23    3  3  2  5  0      1        0
24    3  3  2  5  1      0        0
25    3  3  2  5  2      0        0
26    3  3  2  5  0      0        0
27    3  3  3  2  1      0        1
28    3  3  3  2  2      0        1
29    3  3  3  2  0      0        1
...  .. .. .. .. ..    ...      ...
1698  1  1  4  5  1      0        0
1699  1  1  4  5  2      0        0
1700  1  1  4  5  0      0        0
1701  1  1  5  2  1      0        1
1702  1  1  5  2  2      0        1
1703  1  1  5  2  0      0        1
1704  1  1  5  2  1      1        0
1705  1  1  5  2  2      1        0
1706  1  1  5  2  0      1        0
1707  1  1  5  2  1      0        0
1708  1  1  5  2  2      0        0
1709  1  1  5  2  0      0        0
1710  1  1  5  4  1      0        1
1711  1  1  5  4  2      0        1
1712  1  1  5  4  0      0        1
1713  1  1  5  4  1      1        0
1714  1  1  5  4  2      1        0
1715  1  1  5  4  0      1        0
1716  1  1  5  4  1      0        0
1717  1  1  5  4  2      0        0
1718  1  1  5  4  0      0        0
1719  1  1  5  5  1      0        1
1720  1  1  5  5  2      0        1
1721  1  1  5  5  0      0        1
1722  1  1  5  5  1      1        0
1723  1  1  5  5  2      1        0
1724  1  1  5  5  0      1        0
1725  1  1  5  5  1      0        0
1726  1  1  5  5  2      0        0
1727  1  1  5  5  0      0        0

[1728 rows x 7 columns]

In [12]:
from sklearn import preprocessing
le = preprocessing.LabelEncoder()
y_label=le.fit_transform(y_label)##encoding the labels
print(y_label)

[2 2 2 ... 2 1 3]

In [33]:
print(y_label)
X_train, X_test, y_train, y_test = train_test_split(df,y_label, random_state = 0,shuffle=False) ##splitting the data into training nad testing
print(y_test.shape)
from sklearn.svm import SVC  ##support vector machine for classification
clf = SVC(C=10,kernel='rbf').fit(X_train, y_train)
print(clf.score(X_train,y_train))
print(clf.score(X_test,y_test))

[2 2 2 ... 2 1 3]
(432,)
0.9976851851851852
0.8935185185185185

In [27]:
from sklearn.dummy import DummyClassifier ##cheking the imbalancing of the datset by creating a dummy classifier based on most frequent strategy
dummy=DummyClassifier(strategy='most_frequent').fit(X_train,y_train)
print(dummy.score(X_test,y_test))
y_dummy_predictions = dummy.predict(X_test) ## the accuracy came around 60% while the SVC accuracy was 90% hence it is cleared that the model i mad is not imbalanced

0.5972222222222222